### ISSUE TITLE
build fails indeterministically on openshift 3.0.2

### ISSUE THREAD

**Issue by ivanthelad** [openshift/nodejs-ex#27]
No sure if this belongs to STI builder or this application. It only occurs for this application 

The behaviour 
 - First build is successful
 -Successive builds fail in deterministically with same failure. some fail repeatedly other are succesfully.

I don't understand this as the build always the same.  irregardless if builds occurred before hand.  

Update: The nodejs-ex is build by stepping through the new-app process from the webconsole in ose
 -  add to project
 - use github repo https://github.com/openshift/nodejs-ex#master (try it out)
 - Click next. and then next again

[root@master-ose ~]# oc logs nodejs-ex-5-build
I1103 07:05:50.475738       1 sti.go:74] The value of ALLOWED_UIDS is [1-]
I1103 07:05:50.500131       1 docker.go:211] Image registry.access.redhat.com/openshift3/nodejs-010-rhel7:v3.0.2.0 available locally
I1103 07:05:50.500184       1 sti.go:96] Creating a new S2I builder with build config: "Builder Name:\t\tNode.js 0.10\nBuilder Image:\t\tregistry.access.redhat.com/openshift3/nodejs-010-rhel7:v3.0.2.0\nSource:\t\t\thttps://github.com/openshift/nodejs-ex\nSource Ref:\t\tmaster\nOutput Image Tag:\t172.30.31.42:5000/demo/nodejs-ex:latest\nEnvironment:\t\tOPENSHIFT_BUILD_NAME=nodejs-ex-5,OPENSHIFT_BUILD_NAMESPACE=demo,OPENSHIFT_BUILD_SOURCE=https://github.com/openshift/nodejs-ex,OPENSHIFT_BUILD_REFERENCE=master\nIncremental Build:\tdisabled\nRemove Old Build:\tdisabled\nForce Pull:\t\tdisabled\nQuiet:\t\t\tdisabled\nLayered Build:\t\tdisabled\nDocker Endpoint:\tunix:///var/run/docker.sock\n"
I1103 07:05:50.503270       1 docker.go:211] Image registry.access.redhat.com/openshift3/nodejs-010-rhel7:v3.0.2.0 available locally
I1103 07:05:50.509187       1 sti.go:124] Preparing to build 172.30.31.42:5000/demo/nodejs-ex:latest
I1103 07:05:50.530909       1 clone.go:30] Cloning sources and all GIT submodules into "/tmp/sti549162237/upload/src"
Already on 'master'
I1103 07:05:52.649009       1 clone.go:43] Checked out "master"
I1103 07:05:52.660495       1 docker.go:211] Image registry.access.redhat.com/openshift3/nodejs-010-rhel7:v3.0.2.0 available locally
I1103 07:05:52.660512       1 docker.go:317] Image contains io.openshift.s2i.scripts-url set to 'image:///usr/local/sti'
I1103 07:05:52.660528       1 download.go:57] Using image internal scripts from: image:///usr/local/sti/assemble
I1103 07:05:52.660535       1 download.go:57] Using image internal scripts from: image:///usr/local/sti/run
I1103 07:05:52.663826       1 docker.go:211] Image registry.access.redhat.com/openshift3/nodejs-010-rhel7:v3.0.2.0 available locally
I1103 07:05:52.663838       1 docker.go:317] Image contains io.openshift.s2i.scripts-url set to 'image:///usr/local/sti'
I1103 07:05:52.663850       1 download.go:57] Using image internal scripts from: image:///usr/local/sti/save-artifacts
I1103 07:05:52.663857       1 sti.go:199] Using assemble from image:///usr/local/sti
I1103 07:05:52.663864       1 sti.go:199] Using run from image:///usr/local/sti
I1103 07:05:52.663867       1 sti.go:199] Using save-artifacts from image:///usr/local/sti
I1103 07:05:52.663886       1 sti.go:132] Clean build will be performed
I1103 07:05:52.663890       1 sti.go:135] Performing source build from https://github.com/openshift/nodejs-ex
I1103 07:05:52.663893       1 sti.go:145] Running S2I script in 172.30.31.42:5000/demo/nodejs-ex:latest
I1103 07:05:52.663899       1 sti.go:345] Using image name registry.access.redhat.com/openshift3/nodejs-010-rhel7:v3.0.2.0
I1103 07:05:52.663905       1 sti.go:349] No .sti/environment provided (no environment file found in application sources)
I1103 07:05:52.668226       1 docker.go:317] Image contains io.openshift.s2i.scripts-url set to 'image:///usr/local/sti'
I1103 07:05:52.668241       1 docker.go:370] Base directory for STI scripts is '/usr/local/sti'. Untarring destination is '/tmp'.
I1103 07:05:52.668248       1 docker.go:497] Creating container using config: {Hostname: Domainname: User: Memory:0 MemorySwap:0 CPUShares:0 CPUSet: AttachStdin:false AttachStdout:true AttachStderr:false PortSpecs:[] ExposedPorts:map[] Tty:false OpenStdin:true StdinOnce:true Env:[OPENSHIFT_BUILD_NAME=nodejs-ex-5 OPENSHIFT_BUILD_NAMESPACE=demo OPENSHIFT_BUILD_SOURCE=https://github.com/openshift/nodejs-ex OPENSHIFT_BUILD_REFERENCE=master] Cmd:[/bin/sh -c tar -C /tmp -xf - && /usr/local/sti/assemble] DNS:[] Image:registry.access.redhat.com/openshift3/nodejs-010-rhel7:v3.0.2.0 Volumes:map[] VolumesFrom: WorkingDir: MacAddress: Entrypoint:[] NetworkDisabled:false SecurityOpts:[] OnBuild:[] Mounts:[] Labels:map[]}
I1103 07:05:53.045616       1 docker.go:508] Attaching to container
I1103 07:05:53.046242       1 docker.go:514] Starting container
I1103 07:05:53.289665       1 docker.go:448] Waiting for container
I1103 07:05:53.351494       1 sti.go:407] ---> Installing application source
I1103 07:05:53.361945       1 sti.go:407] ---> Building your Node application from source
E1103 07:05:53.604255       1 util.go:85] npm info it worked if it ends with ok
E1103 07:05:53.604377       1 util.go:85] npm info using npm@1.4.28
E1103 07:05:53.604403       1 util.go:85] npm info using node@v0.10.35
E1103 07:05:53.688222       1 util.go:85] npm info preinstall nodejs-ex@0.0.1
E1103 07:05:53.697534       1 util.go:85] npm ERR! Error: Attempt to unlock ejs@*, which hasn't been locked
E1103 07:05:53.697571       1 util.go:85] npm ERR!     at unlock (/opt/rh/nodejs010/root/usr/lib/node_modules/npm/lib/utils/locker.js:44:11)
E1103 07:05:53.697761       1 util.go:85] npm ERR!     at cb (/opt/rh/nodejs010/root/usr/lib/node_modules/npm/lib/cache/add-named.js:32:5)
E1103 07:05:53.697786       1 util.go:85] npm ERR!     at /opt/rh/nodejs010/root/usr/lib/node_modules/npm/lib/cache/add-named.js:41:20
E1103 07:05:53.697791       1 util.go:85] npm ERR!     at /opt/rh/nodejs010/root/usr/lib/node_modules/npm/lib/utils/locker.js:30:7
E1103 07:05:53.697796       1 util.go:85] npm ERR!     at cb (/opt/rh/nodejs010/root/usr/lib/node_modules/lockfile/lockfile.js:149:38)
E1103 07:05:53.697805       1 util.go:85] npm ERR!     at /opt/rh/nodejs010/root/usr/lib/node_modules/lockfile/lockfile.js:177:38
E1103 07:05:53.698060       1 util.go:85] npm ERR!     at Object.oncomplete (fs.js:108:15)
E1103 07:05:53.698075       1 util.go:85] npm ERR! If you need help, you may report this *entire* log,
E1103 07:05:53.698092       1 util.go:85] npm ERR! including the npm and node versions, at:
E1103 07:05:53.698105       1 util.go:85] npm ERR!     <http://github.com/npm/npm/issues>
E1103 07:05:53.698109       1 util.go:85]
E1103 07:05:53.698112       1 util.go:85] npm ERR! System Linux 3.10.0-229.14.1.el7.x86_64
E1103 07:05:53.698196       1 util.go:85] npm ERR! command "node" "/opt/rh/nodejs010/root/usr/bin/npm" "install" "-d"
E1103 07:05:53.698203       1 util.go:85] npm ERR! cwd /opt/app-root/src
E1103 07:05:53.698250       1 util.go:85] npm ERR! node -v v0.10.35
E1103 07:05:53.698430       1 util.go:85] npm ERR! npm -v 1.4.28
E1103 07:05:53.713447       1 util.go:85] npm info trying registry request attempt 1 at 07:05:53
E1103 07:05:53.713820       1 util.go:85] npm http GET https://registry.npmjs.org/express
E1103 07:05:53.731611       1 util.go:85] npm info trying registry request attempt 1 at 07:05:53
E1103 07:05:53.734940       1 util.go:85] npm http GET https://registry.npmjs.org/mongodb
E1103 07:05:54.147510       1 util.go:85] npm http 200 https://registry.npmjs.org/express
E1103 07:05:54.205382       1 util.go:85] npm info retry fetch attempt 1 at 07:05:54
E1103 07:05:54.206209       1 util.go:85] npm http GET https://registry.npmjs.org/express/-/express-4.13.3.tgz
E1103 07:05:54.342950       1 util.go:85] npm http 200 https://registry.npmjs.org/mongodb
E1103 07:05:54.384705       1 util.go:85] npm http 200 https://registry.npmjs.org/express/-/express-4.13.3.tgz
E1103 07:05:54.391850       1 util.go:85] npm info retry fetch attempt 1 at 07:05:54
E1103 07:05:54.392231       1 util.go:85] npm http GET https://registry.npmjs.org/mongodb/-/mongodb-2.0.47.tgz
E1103 07:05:54.563384       1 util.go:85] npm http 200 https://registry.npmjs.org/mongodb/-/mongodb-2.0.47.tgz
E1103 07:05:54.852918       1 util.go:85] npm ERR!
E1103 07:05:54.852958       1 util.go:85] npm ERR! Additional logging details can be found in:
E1103 07:05:54.853209       1 util.go:85] npm ERR!     /opt/app-root/src/npm-debug.log
E1103 07:05:54.853401       1 util.go:85] npm ERR! not ok code 0
I1103 07:05:55.125285       1 docker.go:450] Container wait returns with 1 and <nil>
I1103 07:05:55.125315       1 docker.go:457] Container exited
I1103 07:05:55.134577       1 cleanup.go:23] Removing temporary directory /tmp/sti549162237
I1103 07:05:55.134591       1 fs.go:99] Removing directory '/tmp/sti549162237'
F1103 07:05:55.135842       1 builder.go:54] Build error: non-zero (13) exit code from registry.access.redhat.com/openshift3/nodejs-010-rhel7:v3.0.2.0

**Comment by ivanthelad** [comment]
ok, there is already a issue related to this under the sti-nodejs project. Closing 
https://github.com/openshift/sti-nodejs/issues/73
